apiVersion: apps/v1 
kind: Deployment
metadata:
  name: pesbuk
  namespace: stagging
  labels:
    app: pesbuk
spec:
  selector:
    matchLabels:
      app: pesbuk
  replicas: 3 
  template: 
    metadata:
      labels:
        app: pesbuk
    spec:
      containers:
      - name: pesbuk
        image: ikhsannugs/pesbuk
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "staging-pesbuk.citrm16v9p2y.ap-southeast-1.rds.amazonaws.com"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: DB_NAME
          value: "pesbukdb"

---
apiVersion: v1
kind: Service
metadata:
  name: pesbuk-stag
  namespace: stag
  labels:
      app: pesbuk
spec:
  type: NodePort
  selector:
    app: pesbuk
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 80

