apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:                               #main container
        - name: mysql
          image: mysql:5.7
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - name: mysql
              protocol: TCP
              containerPort: 3306
          env:                                #environment key
            - name: MYSQL_ROOT_PASSWORD       #nama nya harus sesuai ama key
              valueFrom:
                secretKeyRef:
                  name: mysql-rahasia
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-rahasia
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-rahasia
                  key: MYSQL_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-rahasia
                  key: MYSQL_DATABASE
          volumeMounts:                       #volume mounts
            - name: dump
              mountPath: /docker-entrypoint-initdb.d        #initdb
            - name: data
              mountPath: /var/lib/mysql
      volumes:                                #pvc claim
      - name: dump
        configMap:
          name: mysqldump
      - name: data
        persistentVolumeClaim:
          claimName: mysql-pvc