apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqldump
data:
  initdb.sql: |
    SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
    SET time_zone = "+00:00";

    CREATE DATABASE `pesbuk`;
    use `pesbuk`;
    
    CREATE TABLE `users` (
    `id` int(11) NOT NULL,
    `username` varchar(255) NOT NULL,
    `email` varchar(255) NOT NULL,
    `password` varchar(255) NOT NULL,
    `name` varchar(255) NOT NULL,
    `photo` varchar(255) NOT NULL DEFAULT 'default.svg'
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;
   
    INSERT INTO `users` (`id`, `username`, `email`, `password`, `name`, `photo`) VALUES
    (1, 'rahman', 'rahman@cilsy.id', '$2y$10$HIEq2w.8Et9RsJmY4TMKye4aVCxOd9xJTOtG4vyOEmo.GIBxaPQHK', 'Rahman Rizal', 'default.svg'),
    (3, 'rizal', 'rizal@cilsy.id', '$2y$10$uXa.Hz9rr8gkv4ztaqf6FO84iW64gXHbeyEOy1tIQ5wmqMjTk0yQa', 'Rizal Rahman', 'default.svg');
    
    ALTER TABLE `users`
    ADD PRIMARY KEY (`id`),
    ADD UNIQUE KEY `username` (`username`);
    ALTER TABLE `users`
    MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;