apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk-deployment
  labels:
    app: pesbuk
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pesbuk
  template:
    metadata:
      labels:
        app: pesbuk
    spec:
      containers:
      - name: pesbuk
        image: seargex/sosmed:latest
        ports:
        - containerPort: 80
        env:
          - name: DB_PASS #pass secret
            valueFrom:
              secretKeyRef:
                name: pesbuk-rahasia
                key: DB_PASS
          - name: DB_USER #user secret
            valueFrom:
              secretKeyRef:
                name: pesbuk-rahasia
                key: DB_USER
          - name: DB_HOST #configmap
            valueFrom:
              configMapKeyRef:
                name: pesbuk-konfig
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              configMapKeyRef:
                name: pesbuk-konfig
                key: DB_NAME